const products = [
    {id:1, productName:'Lavanda Blanca', image:'../images/lavanda-blanca-1.jpg', descripcionTitulo:'Lavanda angustifolia',descripcion:'Esta lavanda no es la común, pues sus floración en color blanco la convierten en una de las más deseadas y difíciles de encontrar. De un intenso aroma, necesitará unas características propias del clima mediterráneo para desarrollarse feliz. Es una planta aromática muy rústica, por lo que su riego ideal es escaso. Resistente al frío, se recomienda cultivarla en exterior. Atrae polinizadores', precio: 13, stock: 20 },
    {id:2, productName:'Mini Olivo', image: '../images/olivo.jpg',descripcionTitulo: 'Olea europaea',descripcion:'No hay nada más mediterráneo que tener un olivo en casa. Hazte con este maravilloso árbol y disfruta de su compañía por muchos años. El olivo necesita luz abundante, por lo que se recomienda ponerlo a sol directo. Respecto al riego, mejor escaso, aunque al ser un olivo pequeño en maceta y joven, es posible que necesite una mayor frecuencia de riego. Recuerda que los olivos son plantas de climas cálidos, secos y con mucho sol.',  precio: 25, stock: 3 },
    {id:3, productName:'Mini Limonero', image: '../images/limonero.jpg', descripcionTitulo: 'Citrus limonum Risso',descripcion: 'Los limoneros son árboles que tardan en dar frutos. Lo habitual es que florezca dos veces al año (de marzo a junio y de agosto a octubre). Los frutos suelen madurar durante el otoño y el invierno. Poda los chupones para que tu limonero tenga una buena producción. Es posible que se reciba sin frutos dependiendo de la temporada y su ciclo natural', precio: 30, stock: 15 },
    {id:4, productName:'Mini Naranjo', image: '../images/naranjo.jpg',descripcionTitulo: 'Calamondin Orange',descripcion:'Este naranjo de pequeños frutos es originario de oriente aunque se cultiva ampliamente en Hawai, Estados Unidos y Europa. A menudo, se ofrece como regalo durante el año nuevo chino para dar buena suerte. Produce una floración muy aromática a finales de marzo y sus frutos maduran en noviembre, alcanzando hasta 4cm de diámetro . Sus naranjas son muy ácidas para comer en crudo pero se utilizan a menudo para conservas y mermeladas.', precio: 25, stock: 20 },
    {id:5, productName:'Schefflera', image: '../images/Schefflera.jpg',descripcionTitulo:'Heptapleurum arboricolum',descripcion:'Una planta super resistente y de rápido crecimiento, perfecta para decorar terrazas y jardines. Es tolerante a una gran variedad de condiciones de luz y riego, lo que la convierte en una planta muy deseada y popular para usar en exteriores. Puede prosperar en interiores con luz indirecta brillante y prefiere climas cálidos. Esta planta es apreciada por su capacidad para purificar el aire y su capacidad para crecer en condiciones diversas, lo que la hace adecuada para diferentes tipos de entornos y niveles de experiencia en jardinería.', precio: 20, stock: 40 },
    {id:6, productName:'Celiosa Mix', image: '../images/Celiosa-Mix.jpg',descripcionTitulo:'Ptilotus Joey', descripcion:'El Ptilotus Joey es una planta verdaderamente única que agrega un toque de encanto y exotismo a cualquier jardín o espacio interior. Originaria de Australia, esta belleza llamativa es conocida por sus coloridas espigas de flores que parecen pequeños pompones de terciopelo. Imagina estas delicadas espigas, que varían en color desde el rosa suave hasta el púrpura vibrante, emergiendo de un follaje verde plateado suave y esponjoso. Su aspecto simplemente te flecha, y seguro que será el centro de atención en cualquier rincón donde decidas colocarlo.', precio: 13, stock: 60 },
    {id:7, productName:'Mini Kumquat', image: '../images/mini-kumquat.jpg', descripcionTitulo:'Fortunella crassifolia', descripcion:'Originario de China, este pequeño árbol de cítricos es una delicia tanto para la vista como para el paladar.Para cuidarlo, solo necesitas un poco de sol y amor. Colócalo en un lugar soleado donde pueda recibir luz directa durante al menos unas horas al día. Riégalo regularmente para mantener el sustrato húmedo pero no empapado, y asegúrate de que tenga un buen drenaje para evitar el encharcamiento. El mini kumquat es bastante resistente, pero también le gusta un poco de atención adicional. Puedes alimentarlo con un fertilizante como humus líquido para plantas de cítricos durante la primavera y el verano para ayudarlo a crecer y prosperar.', precio: 25, stock: 30 },
    {id:8, productName:'Aloe Vera', image: '../images/aloe-vera.jpg',descripcionTitulo:'Aloe barbadensis',descripcion:'El Aloe Vera, conocida por sus hojas carnosas llenas de gel calmante será esa planta resistente y fácil de cuidar que necesitarás tener. Originaria del norte de África, es una campeona en adaptarse a ambientes secos y soleados. Cuidarla es muy fácil: solo necesitas colocarla en un lugar con mucha luz, preferible sol directo y regarla de vez en cuando, dejando que el suelo se seque completamente entre riegos. Además, es genial para tener en casa porque su gel tiene muchísimos usos, desde calmar quemaduras hasta hidratar la piel. ¡Es una planta tan práctica como bonita!', precio: 10, stock: 80 },
    {id:9, productName:'Lavanda Morada', image: '../images/lavanda-morada.jpg',descripcionTitulo:'Lavandula angustifolia',descripcion:'Si siempre soñaste con tener lavanda en casa, aquí ha llegado tu árbol. Esta lavanda morada es mucho más que una planta, es un aromático árbol perfecto para cultivar en balcones, terrazas o jardines. Para cuidarlo, recomendamos colocarlo en un lugar donde reciba al menos seis horas de sol directo al día.', precio: 20, stock: 20 },
    {id:11, productName:'Cordyline L', image: '../images/cordyline.jpg',descripcionTitulo:'Cordyline australis',descripcion:'Esta exótica planta se puede cultivar en interiores o exteriores cálidos, luz en semi sombra y riegos frecuentes pero poco abundantes. Agradece que se fertilice orgánicamente cada 15 días durante el riego con humus de lombriz líquido. Sus hojas rosadas darán un toque de color a tu terraza o balcón.', precio: 30, stock: 35 },
    {id:12, productName:'Olivo Manzanillo',image: '../images/manzanillo.jpg',descripcionTitulo:'Olea Europea Manzanillo',descripcion:'No hay mediterráneo sin olivo. Este increíble árbol de olivo Olea Europea Manzanillo es muy fácil de cuidar en exterior y suele adaptarse fácilmente al entorno. Aunque también se puede cultivar en maceta, recuerda que el olivo crece feliz a pleno sol, siempre que reciba entre 5 o 6h diarias.En cuanto a la forma, estos árboles pueden variar en función del ejemplar en tamaño, forma y grosor de tronco.Recomendamos abonar con nuestro humus de lombriz líquido durante los riegos mensuales y también agradece  biopellet en su sustrato.' , precio: 100, stock: 2 },
    {id:13, productName:'Cactus', image: '../images/cactus.jpg',descripcionTitulo:'Opuntia Microdasys',descripcion:'Esta belleza de cactus con sus palas redondeadas darán un toque único a nuestros espacios. El sustrato orgánico perfecto para esta especie es el que tenemos disponible como sustrato para cactus y suculentas. Prefiere las macetas de terracota. También te recomendamos añadir un chorrito de humus de lombriz líquido como fertilizante en primavera y al comienzo del otoño. Un plantip: una forma de estimular su crecimiento es sacarlo a un balcón orientación sur durante los meses de verano.', precio: 30, stock: 25 },
    {id:14, productName:'Eugenia', image: '../images/eugenia.jpg',descripcionTitulo:'Eugenia uniflora',descripcion:' Esta planta es considerada uno de los arbustos más populares para usar como valla vegetal en exteriores y jardines. Prefiere lugares sombríos, aunque también se adapta a lugares con pleno sol. Plantip: cuanto más poda recibe, más frondoso es su follaje', precio: 35, stock: 15 },
    {id:15, productName:'Opuntia', image: '../images/opuntia.jpg', descripcionTitulo:'Opuntia microdasys Pfeiffer',descripcion:'Esta belleza de cactus con sus palas redondeadas y en tonos amarillos darán un toque de color a nuestros espacios. El sustrato orgánico perfecto para esta especie es el que tenemos disponible como sustrato para cactus y suculentas. Prefiere las macetas de terracota.También te recomendamos añadir un chorrito de humus de lombriz líquido como fertilizante en primavera y al comienzo del otoño. Un plantip: una forma de estimular su crecimiento es sacarlo a un balcón orientación sur durante los meses de verano.',precio: 40, stock: 12},
    {id:16, productName:'Callistemon', image: '../images/callistemon-citrinus.jpg',descripcionTitulo:'Callistemon citrinus', descripcion:'Originario de Australia, este arbusto perenne es una explosión de color y alegría en cualquier jardín.Imagina tener a este llamativo árbol en tu patio trasero: con sus brillantes flores rojas que se asemejan a cepillos para botellas. Cuidar del Callistemon citrinus es bastante sencillo. Asegúrate de plantarlo en un suelo bien drenado y con un buen acceso a la luz solar. El riego regular es importante durante su temporada de crecimiento (prefiere mantener sustrato ligeramente húmedo), pero también aprecia un poco de sequedad entre riegos para evitar problemas de pudrición de raíces (sobre todo en otoño e invierno)', precio: 50, stock: 60 },
]


